import Head from 'next/head'
import { Montserrat } from 'next/font/google'

import Title from '@/components/Title'
import Input from '@/components/Input'
import Status from '@/components/Status'
import Footer from '@/components/Footer'

import styles from '@/styles/Home.module.css'
import Button from '@/components/Button'

const montserrat = Montserrat({ subsets: ["latin"] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Validador de CPF</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.container} ${montserrat.className}`}>
      <Title />
      <div className={styles.verifyInput}>
        <Input/>
        <Button/>
      </div>
      <Status/>
      <Footer/>
      </main>
    </>
  )
}
